# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "faraday", "~> 1"
gem "rack", "~> 2"
gem "pry", "~> 0.14"
gem "rake", "~> 13"
gem "rspec", "~> 3"
gem "rspec_junit_formatter", "~> 0.4"
gem "yard", "~> 0.9"
gem "activerecord", "~> 6.1"
gem "mysql2", "~> 0.5"
gem "pg", "~> 1"

gem "standard", require: false
