name: Test Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.15.x', '1.16.x', '1.17.x' ]
    steps:
    - uses: actions/checkout@v3.5.2
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - run: go test -race -timeout=10s -parallel=4 ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.41
