name: Release Ruby
on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: gem update --system
        working-directory: ruby
      - run: git config --global user.email github-action@users.noreply.github.com
        working-directory: ruby
      - run: git config --global user.name GitHub Actions
        working-directory: ruby
      - run: git config --global user.password ${{ github.token }}
        working-directory: ruby
      - run: bundle install
        working-directory: ruby
      - run: bundle exec rake release
        working-directory: ruby
        env:
          GEM_HOST_API_KEY: "Bearer ${{ github.token }}"
