name: Test Ruby
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: shed_test
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout
          5s --health-retries 5
        ports:
        - 3306:3306
      postgres:
        image: postgres
        env:
          POSTGRES_USER: runner
          POSTGRES_DB: shed_test
          POSTGRES_PASSWORD: postgres
        options: "--health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5"
        ports:
        - 5432:5432
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6', '2.7', '3.0' ]
    name: ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: gem install bundler:2.1.4
      - run: bundle install
        working-directory: ruby
      - run: bundle exec rspec --format progress
        working-directory: ruby
      - run: bundle exec standardrb
        working-directory: ruby
